### ISSUE TITLE
Add or update external resources

### ISSUE THREAD

**Issue by mcanulavantronics** [eclipse-keyple/keyple-website#204]
### Name of the company that provides the resources

Avantronics S.A De C.V.

### Types of products or services provided (multiple options can be selected)

Tools, Development

### Short description (sentence 1)

Soluciones tecnológicas para el transporte público, especializadas en el desarrollo de herramientas que optimizan la movilidad.

### External page URL

https://avantronics.com.mx/

**Comment by jeanpierrefortune** [comment]
Hi M. Canul,

Please be advised that we have updated the issue form you previously used to submit your information.

From now, you will need to submit your organization's logo to be listed among Keyple adopters on the Eclipse Foundation website (https://iot.eclipse.org/adopters/). This will provide your organization with visibility on a well-known platform.

To proceed, please apply directly through Eclipse (https://gitlab.eclipse.org/eclipsefdn/it/api/eclipsefdn-project-adopters/-/issues/new?issuable_template=adopter_request) or submit your logo here by attaching your logo here.

Please note that we require both color options for logos for distribution purposes.
- We need color logo with transparent background.
- We also need white logo with a transparent background.

Could you please follow one of these procedures?

Thank you in advance.

Best regards

**Comment by mcanulavantronics** [comment]
Hello Jean, have a great day.

Right here I attach the logos as you request them, I am awaiting your confirmation or any additional information that you request. Excellent day.
![AVANTRONICS BLANCO](https://github.com/eclipse-keyple/keyple-website/assets/146114227/c092eeaa-f2d6-4568-80bc-5dd85de8cc58)
![AVANTRONICS COLOR](https://github.com/eclipse-keyple/keyple-website/assets/146114227/3f28bf00-ace5-450c-bba9-1dd8d13ff10f)
